---
- name: Install qBittorrent
  become: true
  tags: qbittorrent
  block:
    - name: Create system user
      user:
        name: qbittorrent
        system: true
        shell: /usr/sbin/nologin
        home: /var/lib/qbittorrent
        skeleton: /dev/null

    - name: Add users to the group
      user:
        name: "{{ item }}"
        groups: qbittorrent
        append: true
      with_items: "{{ qbittorrent_users }}"

    - name: Install
      apt:
        name: qbittorrent-nox
        update_cache: true

    - name: Create config directory
      file:
        name: /var/lib/qbittorrent/.config/qBittorrent/
        state: directory
        owner: qbittorrent
        group: qbittorrent
        mode: '0755'

    - name: Accept legal notice
      community.general.ini_file:
        path: /var/lib/qbittorrent/.config/qBittorrent/qBittorrent.conf
        section: LegalNotice
        option: Accepted
        value: 'true'
        owner: qbittorrent
        group: qbittorrent
        mode: '0644'
        no_extra_spaces: true
      notify: Restart qBittorrent

    - name: Configure service
      service:
        name: qbittorrent-nox@qbittorrent
        state: started
        enabled: true
      register: qbittorrent_service
